// This is a dummy file for now, will be generated by build_frequency_lists.py

#ifndef __ZXCVBN__FREQUENCY_LISTS_HPP
#define __ZXCVBN__FREQUENCY_LISTS_HPP

namespace zxcvbn {

enum class DictionaryTag {
  PASSWORDS,
  ENGLISH_WIKIPEDIA,
  SURNAMES,
  MALE_NAMES,
  FEMALE_NAMES,
};

}

#endif
